chrome.webRequest.onBeforeRequest.addListener(
  function(info) {
    return {redirectUrl: 'http://eff.org'};
  },
  // filters
  {
    urls: [

      "*://*.google.com/*",
      "*://*.466453.com/*",
      "*://*.1e100.com/*",
      "*://*.AdSense.com/*",
      "*://*.AdWords.com/*",
      "*://*.Android.com/*",
      "*://*.blogger.com/*",
      "*://*.blogspot.com/*",
      "*://*.chromium.com/*",
      "*://*.DoubleClick.com/*",
      "*://*.FeedBurner.com/*",
      "*://*.froogle.com/*",
      "*://*.ggpht.com/*",
      "*://*.gogle.com/*",
      "*://*.gogole.com/*",
      "*://*.google.net/*",
      "*://*.google.org/*",
      "*://*.googil.com/*",
      "*://*.googleapis.com/*",
      "*://*.googleapps.com/*",
      "*://*.googlebot.com/*",
      "*://*.googleratings.com/*",
      "*://*.googlr.com/*",
      "*://*.gooogle.com/*",
      "*://*.gstatic.com/*",
      "*://*.gtempaccount.com/*",
      "*://*.igoogle.com/*",
      "*://*.keyhole.com/*",
      "*://*.panoramio.com/*",
      "*://*.like.com/*",
      "*://*.Sketchup.com/*",
      "*://*.Picasa.com/*",
      "*://*.googleusercontent.com/*",
      "*://*.youtu.be/*",
      "*://*.youtube.com/*",

      /* YAHOO */
      "*://*.flickr.com/*",
      "*://*.yahoo.com/*",
      "*://*.foxytunes.com/*",
      "*://*.upcoming.org/*",
      "*://*.wretch.cc/*",
      "*://*.rivals.com/*",
      "*://*.tumblr.com/*",
      "*://*.maktoob.com/*",
      "*://*.tahadi.com/*",
      "*://*.sukar.com/*",
      "*://*.citizensports..com/*",
      "*://*.stamped.com/*",
      "*://*.snip.it/*",
      "*://*.astrid.com/*",
      "*://*.koprol.com/*",
      "*://*.y.ahoo.it/*",
      "*://*.kelkoo.com/*",
      "*://*.bix.com/*",
      /* FACEBOOK */
      "*://*.drop.io/*",
      "*://*.mailrank.com/*",
      "*://*.friend.ly/*",
      "*://*.facebook.com/*",
      "*://*.facebook.net/*",
      "*://*.fbook.com/*",
      "*://*.parse.com/*",
      "*://*.threadsy.com/*",
      "*://*.getspool.com/*",
      "*://*.fb.com/*",
      "*://*.instagram.com/*",
      "*://*.instagr.am/*",
      /* APPLE */
      "*://*.apple.com/*",
      "*://*.Airport.com/*",
      "*://*.Applecomputer.com/*",
      "*://*.Appleimac.com/*",
      "*://*.Carbon.com/*",
      "*://*.Buy-Different.com/*",
      "*://*.DesktopMovie.com/*",
      "*://*.BuyAAPL.com/*",
      "*://*.DigitalHub.com/*",
      "*://*.Dvdstudiopro.com/*",
      "*://*.FireWire.org/*",
      "*://*.iMac.org/*",
      "*://*.iPhone.com/*",
      "*://*.iMac.com/*",
      "*://*.iPodRocks.com/*",
      "*://*.PublishingResearch.com/*",
      "*://*.PublishingSurvey.com/*",
      "*://*.Xserve.com/*",
      "*://*.Xserve.net/*",
      "*://*.iMac.com/*",
      "*://*.iWork.com/*",
      "*://*.iChat.com/*",
      "*://*.Applemusic.com/*",
      "*://*.FinalCutPro.com/*",
      "*://*.iPod.com/*",
      "*://*.mac.com/*",
      "*://*.Quicktime.com/*",
       /* MICROSOFT */
       "*://*.microsoft.com/*",
       "*://*.msn.com/*",
       "*://*.xbox.com/*",
       "*://*.bing.com/*",
       "*://*.halowaypoint.com/*",
       "*://*.windows.com/*",
       "*://*.hotmail.com/*",
       "*://*.kinect.com/*",
       "*://*.xboxone.com/*",
       "*://*.live.com/*",
       /* DROPBOX */
       "*://*.dropbox.com/*",
       "*://*.getdropbox.com/*",
       "*://*.getdropbox.com/*"
    ], 
    types: ["main_frame", "sub_frame", "stylesheet", "script", "image", "object", "xmlhttprequest", "other"] 
  },
  // extraInfoSpec
  ["blocking"]);
/*


    ]
    */